### PR TITLE
Added Products listing page including Filters

### LINKED ISSUE #14: Create Products listing page

### PR DESCRIPTION
**Pull request by kjais1720**
PR for Issue #14 ( closes #14 )
## Overview
- Created products listing page
- FIxed Filters sidebar 
- Updated product cards style for out of stock products
- Fixed responsiveness of the filters sidebar

## Preview
- Preview link - https://crickstock-store-git-feat-create-products-list-bb51ee-kjais1720.vercel.app/
- Preview Image
screenshot (6)

### CODE REVIEW

**Review by ttahm3d — COMMENTED** [review]
NIcely done. 

Everything split into its own files and no overlapping functionalities. One suggestion is that you can style the disable class instead of creating your class and adding it conditionally

**Comment by nishasen** [comment]
In you design part add some gap between filter box and product card

**Review by nishasen — APPROVED** [review]
Good looks clean, good and understandable. I liked how you have reused your code.

**Comment by kjais1720** [comment]
> NIcely done.
> 
> Everything split into its own files and no overlapping functionalities. One suggestion is that you can style the disable class instead of creating your class and adding it conditionally

Whic class are you talking about?

> In you design part add some gap between filter box and product card

Actually that's an issue with the screenshot, actual output doesn't looks like this, the filter sidebar is fixed in the actual output

**Pull request merged**
